// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBUuqWYxVEtCpx37najUeVdPCXlcaNcAI',
    appId: '1:780928801781:web:406251bd768fe03e3c5ebc',
    messagingSenderId: '780928801781',
    projectId: 'wanna-app-d96d0',
    authDomain: 'wanna-app-d96d0.firebaseapp.com',
    storageBucket: 'wanna-app-d96d0.firebasestorage.app',
    measurementId: 'G-0NVKCMEGM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgU5EPNne-vb7qX0Szcen3Is8Q6gs9eCU',
    appId: '1:780928801781:android:dfb025be712fd4333c5ebc',
    messagingSenderId: '780928801781',
    projectId: 'wanna-app-d96d0',
    storageBucket: 'wanna-app-d96d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHJ-6SU7sdB2e3Ee92E13QOoE7c_puLU',
    appId: '1:780928801781:ios:4bf3c738fa62cf083c5ebc',
    messagingSenderId: '780928801781',
    projectId: 'wanna-app-d96d0',
    storageBucket: 'wanna-app-d96d0.firebasestorage.app',
    iosBundleId: 'com.dohome.pos.ppos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHJ-6SU7sdB2e3Ee92E13QOoE7c_puLU',
    appId: '1:780928801781:ios:4bf3c738fa62cf083c5ebc',
    messagingSenderId: '780928801781',
    projectId: 'wanna-app-d96d0',
    storageBucket: 'wanna-app-d96d0.firebasestorage.app',
    iosBundleId: 'com.dohome.pos.ppos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBUuqWYxVEtCpx37najUeVdPCXlcaNcAI',
    appId: '1:780928801781:web:7b721fdcb821d37d3c5ebc',
    messagingSenderId: '780928801781',
    projectId: 'wanna-app-d96d0',
    authDomain: 'wanna-app-d96d0.firebaseapp.com',
    storageBucket: 'wanna-app-d96d0.firebasestorage.app',
    measurementId: 'G-8WMF4HEVC5',
  );
}
